$(document).ready(function(){
	$('#clients_select').change(function(){
		updateForm($(this).val(),'clients',['mongoid','company','client_name','email','phone_number','client_rate']);
	});
	$('#submitBtn').click(function(){
		if(saveDoc('clients',true)){
			reloadFormElement('clients_select_container','clients');
			$('#clients_select').change(function(){
				updateForm($(this).val(),'clients',['mongoid','company','client_name','email','phone_number','client_rate']);
			});
		}
	});
	$('#deleteBtn').click(function(){
		deleteDoc('clients',true);
		reloadFormElement('clients_select_container','clients');
		$('#clients_select').change(function(){
			updateForm($(this).val(),'clients',['mongoid','company','client_name','email','phone_number','client_rate']);
		});
	});
	$('#resetBtn').click(function(){
		reloadPageElements('clients');
		reloadFormElement('clients_select_container','clients');
		$('#clients_select').change(function(){
			updateForm($(this).val(),'clients',['mongoid','company','client_name','email','phone_number','client_rate']);
		});
	});
});